
name: dev

on:
  push:
    branches:
      - dev

jobs:
    call-workflow-deploy-dev:
      uses: GuyPeer85/llay-final-project/.github/workflows/CI-CD.yml@dev
      with:
        infa_env: dev
      secrets: inherit