
name: prod

# branch main the deploy is done by running the workflow manually.
on: 
  workflow_dispatch:
      branches:
      - main

jobs:
  call-workflow-deploy-prod:
    uses: GuyPeer85/llay-final-project/.github/workflows/CI-CD.yml@main
    with:
      infa_env: prod
    secrets: inherit